import Head from 'next/head'
import Header from '../components/Header'
import Slider from '../components/Slider'
import SubHeader from '../components/SubHeader'
import SectionHeader from '../components/SectionHeader'
import FlatCardSection from '../components/FlatCardSection'
import StraightCardSection from '../components/StraightCardSection'
import Footer from '../components/Footer'


const {BLOG_URL, CONTENT_API_KEY} = process.env


const getPosts =async () => {
  
  const res = await fetch(
		`${BLOG_URL}/ghost/api/v3/content/posts/?key=${CONTENT_API_KEY}`
	).then((res) => res.json())

	const posts = res.posts

	return posts

}



export const getStaticProps = async ({ params }) => {
	const posts = await getPosts()
	return {
		revalidate: 10,
		props: { posts }
	}
}



export default function Home({posts}) {
  return (
    <div className='container' >
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <SubHeader />
        <Slider Posts={posts} />
        <SectionHeader slug={'Energy & Environment'}/>
        <FlatCardSection posts={posts} slug={'Energy & Environment'} Place={true}/>
        <SectionHeader slug={'Physics & Mathematics'} />
        <StraightCardSection slug={'Physics & Mathematics'}  posts={posts} Place={true}/>
        <SectionHeader slug={'Technology'} />
        <FlatCardSection posts={posts}  slug={'Technology'}  Place={true}/>
        <SectionHeader slug={'Space'} />
        <StraightCardSection posts={posts} slug={'Space'}  Place={true}/>
        <Footer />
      </div>
     
    </div>
  )
}
