import Head from 'next/head'
import Header from '../components/Header'
import Slider from '../components/Slider'
import SubHeader from '../components/SubHeader'
import SectionHeader from '../components/SectionHeader'
import FlatCardSection from '../components/FlatCardSection'
import StraightCardSection from '../components/StraightCardSection'
import Footer from '../components/Footer'






export default function Home() {
 
  return (
    <div className='container' >
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <SubHeader />
        <Slider />
        <SectionHeader CategoryName={'Energy & Environment'}/>
        <FlatCardSection CategoryName={'Energy & Environment'} Place='home' />
        <SectionHeader CategoryName={'Physics & Mathematics'} />
        <StraightCardSection CategoryName={'Physics & Mathematics'}  Place='home'/>
        <SectionHeader CategoryName={'Technology'} />
        <FlatCardSection CategoryName={'Technology'} />
        <SectionHeader CategoryName={'Space'} />
        <StraightCardSection CategoryName={'Space'} />
        <Footer />
      </div>
     
    </div>
  )
}
